/**
 * Read-only database introspection.
 *
 * Connects to the live Supabase Postgres via DATABASE_URL and emits a Markdown
 * snapshot of the `public` schema: tables + columns, primary/foreign keys,
 * views (including products_with_taxonomy), and RLS status + policies.
 *
 * SELECT-only against system catalogs — does not modify any data.
 *
 *   npx tsx -r dotenv/config scripts/introspect-db.ts dotenv_config_path=.env.local
 */
import postgres from "postgres";

const url = process.env.DATABASE_URL;
if (!url) {
  console.error("DATABASE_URL not set");
  process.exit(1);
}

// Transaction-mode pooler (pgbouncer) does not support prepared statements.
const sql = postgres(url, { prepare: false, max: 1, idle_timeout: 5 });

function esc(s: unknown) {
  return String(s ?? "");
}

async function main() {
  const out: string[] = [];
  out.push("# BIFL — Live DB Schema Snapshot (public schema)");
  out.push("");
  out.push("Read-only introspection of the production Supabase Postgres.");
  out.push("Not a runnable migration — a reference of the live shape. Generated by `scripts/introspect-db.ts`.");
  out.push("");

  const tables = await sql<{ table_name: string; rls: boolean }[]>`
    SELECT c.relname AS table_name, c.relrowsecurity AS rls
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'r'
    ORDER BY c.relname;
  `;

  out.push(`## Tables (${tables.length})`);
  out.push("");

  for (const t of tables) {
    const cols = await sql<
      { column_name: string; data_type: string; is_nullable: string; column_default: string | null }[]
    >`
      SELECT column_name, data_type, is_nullable, column_default
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ${t.table_name}
      ORDER BY ordinal_position;
    `;

    const pks = await sql<{ column_name: string }[]>`
      SELECT kcu.column_name
      FROM information_schema.table_constraints tc
      JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
      WHERE tc.table_schema = 'public' AND tc.table_name = ${t.table_name}
        AND tc.constraint_type = 'PRIMARY KEY'
      ORDER BY kcu.ordinal_position;
    `;

    const fks = await sql<
      { column_name: string; foreign_table: string; foreign_column: string }[]
    >`
      SELECT kcu.column_name,
             ccu.table_name AS foreign_table,
             ccu.column_name AS foreign_column
      FROM information_schema.table_constraints tc
      JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
      JOIN information_schema.constraint_column_usage ccu
        ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema
      WHERE tc.table_schema = 'public' AND tc.table_name = ${t.table_name}
        AND tc.constraint_type = 'FOREIGN KEY';
    `;

    const policies = await sql<
      { policyname: string; cmd: string; roles: string[]; qual: string | null; with_check: string | null }[]
    >`
      SELECT policyname, cmd, roles, qual, with_check
      FROM pg_policies
      WHERE schemaname = 'public' AND tablename = ${t.table_name}
      ORDER BY policyname;
    `;

    out.push(`### \`${t.table_name}\`  ${t.rls ? "🔒 RLS ON" : "⚠️ RLS OFF"}`);
    out.push("");
    out.push("| column | type | null | default |");
    out.push("|---|---|---|---|");
    for (const c of cols) {
      out.push(
        `| ${c.column_name} | ${c.data_type} | ${c.is_nullable} | ${esc(c.column_default).slice(0, 60)} |`
      );
    }
    if (pks.length) out.push(`\nPK: ${pks.map((p) => p.column_name).join(", ")}`);
    if (fks.length)
      out.push(
        `\nFKs: ${fks.map((f) => `${f.column_name} → ${f.foreign_table}.${f.foreign_column}`).join("; ")}`
      );
    if (policies.length) {
      out.push(`\nPolicies (${policies.length}):`);
      for (const p of policies) {
        out.push(
          `- **${p.policyname}** [${p.cmd}] roles=${(p.roles || []).join(",")} using=\`${esc(p.qual).slice(0, 80)}\` check=\`${esc(p.with_check).slice(0, 80)}\``
        );
      }
    } else if (t.rls) {
      out.push(`\n⚠️ RLS enabled but NO policies → table is locked to anon/auth (service role still bypasses).`);
    }
    out.push("");
  }

  const views = await sql<{ viewname: string; definition: string }[]>`
    SELECT viewname, pg_get_viewdef(format('public.%I', viewname)::regclass, true) AS definition
    FROM pg_views WHERE schemaname = 'public' ORDER BY viewname;
  `;
  const matviews = await sql<{ matviewname: string }[]>`
    SELECT matviewname FROM pg_matviews WHERE schemaname = 'public' ORDER BY matviewname;
  `;

  out.push(`## Views (${views.length})`);
  out.push("");
  for (const v of views) {
    out.push(`### \`${v.viewname}\` (view)`);
    out.push("```sql");
    out.push(v.definition.trim());
    out.push("```");
    out.push("");
  }
  if (matviews.length) {
    out.push(`## Materialized views (${matviews.length})`);
    out.push(matviews.map((m) => `- \`${m.matviewname}\``).join("\n"));
    out.push("");
  } else {
    out.push("No materialized views.");
    out.push("");
  }

  process.stdout.write(out.join("\n"));
  await sql.end({ timeout: 5 });
}

main().catch(async (e) => {
  console.error("INTROSPECT FAILED:", e?.message || e);
  try {
    await sql.end({ timeout: 5 });
  } catch {}
  process.exit(1);
});
