// Auto-generated by supabase gen types typescript (2026-07-07). Do not hand-edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      account: {
        Row: {
          accessToken: string | null
          accessTokenExpiresAt: string | null
          accountId: string
          createdAt: string
          id: string
          idToken: string | null
          password: string | null
          providerId: string
          refreshToken: string | null
          refreshTokenExpiresAt: string | null
          scope: string | null
          updatedAt: string
          userId: string
        }
        Insert: {
          accessToken?: string | null
          accessTokenExpiresAt?: string | null
          accountId: string
          createdAt?: string
          id: string
          idToken?: string | null
          password?: string | null
          providerId: string
          refreshToken?: string | null
          refreshTokenExpiresAt?: string | null
          scope?: string | null
          updatedAt?: string
          userId: string
        }
        Update: {
          accessToken?: string | null
          accessTokenExpiresAt?: string | null
          accountId?: string
          createdAt?: string
          id?: string
          idToken?: string | null
          password?: string | null
          providerId?: string
          refreshToken?: string | null
          refreshTokenExpiresAt?: string | null
          scope?: string | null
          updatedAt?: string
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "account_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_users: {
        Row: {
          created_at: string | null
          email: string
          id: string
          is_active: boolean | null
          last_login: string | null
          name: string | null
          password_hash: string
          role: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          email: string
          id?: string
          is_active?: boolean | null
          last_login?: string | null
          name?: string | null
          password_hash: string
          role?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string
          id?: string
          is_active?: boolean | null
          last_login?: string | null
          name?: string | null
          password_hash?: string
          role?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      badges: {
        Row: {
          background_color: string
          created_at: string | null
          description: string | null
          icon_name: string
          id: string
          name: string
          text_color: string
          updated_at: string | null
        }
        Insert: {
          background_color: string
          created_at?: string | null
          description?: string | null
          icon_name: string
          id?: string
          name: string
          text_color?: string
          updated_at?: string | null
        }
        Update: {
          background_color?: string
          created_at?: string | null
          description?: string | null
          icon_name?: string
          id?: string
          name?: string
          text_color?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      brands: {
        Row: {
          country: string | null
          created_at: string | null
          description: string | null
          founded_year: number | null
          id: string
          is_featured: boolean | null
          logo_url: string | null
          name: string
          reputation_score: number | null
          slug: string
          updated_at: string | null
          warranty_info: string | null
          website: string | null
        }
        Insert: {
          country?: string | null
          created_at?: string | null
          description?: string | null
          founded_year?: number | null
          id?: string
          is_featured?: boolean | null
          logo_url?: string | null
          name: string
          reputation_score?: number | null
          slug: string
          updated_at?: string | null
          warranty_info?: string | null
          website?: string | null
        }
        Update: {
          country?: string | null
          created_at?: string | null
          description?: string | null
          founded_year?: number | null
          id?: string
          is_featured?: boolean | null
          logo_url?: string | null
          name?: string
          reputation_score?: number | null
          slug?: string
          updated_at?: string | null
          warranty_info?: string | null
          website?: string | null
        }
        Relationships: []
      }
      buying_guides: {
        Row: {
          buying_criteria: Json | null
          category_id: string | null
          created_at: string | null
          curation_id: string | null
          faqs: Json | null
          featured_image_url: string | null
          id: string
          intro_content: string | null
          is_published: boolean | null
          meta_description: string | null
          meta_title: string | null
          published_at: string | null
          slug: string
          title: string
          updated_at: string | null
        }
        Insert: {
          buying_criteria?: Json | null
          category_id?: string | null
          created_at?: string | null
          curation_id?: string | null
          faqs?: Json | null
          featured_image_url?: string | null
          id?: string
          intro_content?: string | null
          is_published?: boolean | null
          meta_description?: string | null
          meta_title?: string | null
          published_at?: string | null
          slug: string
          title: string
          updated_at?: string | null
        }
        Update: {
          buying_criteria?: Json | null
          category_id?: string | null
          created_at?: string | null
          curation_id?: string | null
          faqs?: Json | null
          featured_image_url?: string | null
          id?: string
          intro_content?: string | null
          is_published?: boolean | null
          meta_description?: string | null
          meta_title?: string | null
          published_at?: string | null
          slug?: string
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "buying_guides_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "buying_guides_curation_id_fkey"
            columns: ["curation_id"]
            isOneToOne: false
            referencedRelation: "curations"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string | null
          description: string | null
          display_order: number | null
          icon_url: string | null
          id: string
          is_featured: boolean | null
          name: string
          parent_id: string | null
          show_buying_guide: boolean | null
          slug: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          icon_url?: string | null
          id?: string
          is_featured?: boolean | null
          name: string
          parent_id?: string | null
          show_buying_guide?: boolean | null
          slug: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          icon_url?: string | null
          id?: string
          is_featured?: boolean | null
          name?: string
          parent_id?: string | null
          show_buying_guide?: boolean | null
          slug?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      certifications: {
        Row: {
          created_at: string | null
          criteria: string | null
          description: string | null
          icon_url: string | null
          id: string
          issuing_body: string | null
          name: string
          slug: string
        }
        Insert: {
          created_at?: string | null
          criteria?: string | null
          description?: string | null
          icon_url?: string | null
          id?: string
          issuing_body?: string | null
          name: string
          slug: string
        }
        Update: {
          created_at?: string | null
          criteria?: string | null
          description?: string | null
          icon_url?: string | null
          id?: string
          issuing_body?: string | null
          name?: string
          slug?: string
        }
        Relationships: []
      }
      curation_products: {
        Row: {
          created_at: string | null
          curation_id: string
          display_order: number | null
          id: string
          product_id: string
        }
        Insert: {
          created_at?: string | null
          curation_id: string
          display_order?: number | null
          id?: string
          product_id: string
        }
        Update: {
          created_at?: string | null
          curation_id?: string
          display_order?: number | null
          id?: string
          product_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "curation_products_curation_id_fkey"
            columns: ["curation_id"]
            isOneToOne: false
            referencedRelation: "curations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "curation_products_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "featured_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "curation_products_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "curation_products_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_with_taxonomy"
            referencedColumns: ["id"]
          },
        ]
      }
      curations: {
        Row: {
          created_at: string | null
          description: string | null
          display_order: number | null
          featured_image_url: string | null
          id: string
          is_active: boolean | null
          is_featured: boolean | null
          name: string
          slug: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          featured_image_url?: string | null
          id?: string
          is_active?: boolean | null
          is_featured?: boolean | null
          name: string
          slug: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          featured_image_url?: string | null
          id?: string
          is_active?: boolean | null
          is_featured?: boolean | null
          name?: string
          slug?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      feedback: {
        Row: {
          attachment_url: string | null
          contact_email: string | null
          contact_name: string | null
          created_at: string | null
          details: string
          feedback_type: string
          id: string
          status: string | null
          subject: string
          updated_at: string | null
        }
        Insert: {
          attachment_url?: string | null
          contact_email?: string | null
          contact_name?: string | null
          created_at?: string | null
          details: string
          feedback_type: string
          id?: string
          status?: string | null
          subject: string
          updated_at?: string | null
        }
        Update: {
          attachment_url?: string | null
          contact_email?: string | null
          contact_name?: string | null
          created_at?: string | null
          details?: string
          feedback_type?: string
          id?: string
          status?: string | null
          subject?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      materials: {
        Row: {
          created_at: string | null
          description: string | null
          durability_factor: number | null
          id: string
          name: string
          slug: string
          sustainability_rating: number | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          durability_factor?: number | null
          id?: string
          name: string
          slug: string
          sustainability_rating?: number | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          durability_factor?: number | null
          id?: string
          name?: string
          slug?: string
          sustainability_rating?: number | null
        }
        Relationships: []
      }
      newsletter_subscribers: {
        Row: {
          created_at: string | null
          email: string
          id: string
          subscribed: boolean | null
          subscribed_at: string | null
          unsubscribed_at: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          email: string
          id?: string
          subscribed?: boolean | null
          subscribed_at?: string | null
          unsubscribed_at?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string
          id?: string
          subscribed?: boolean | null
          subscribed_at?: string | null
          unsubscribed_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      price_ranges: {
        Row: {
          description: string | null
          display_order: number | null
          id: string
          max_price: number | null
          min_price: number | null
          name: string
          slug: string
        }
        Insert: {
          description?: string | null
          display_order?: number | null
          id?: string
          max_price?: number | null
          min_price?: number | null
          name: string
          slug: string
        }
        Update: {
          description?: string | null
          display_order?: number | null
          id?: string
          max_price?: number | null
          min_price?: number | null
          name?: string
          slug?: string
        }
        Relationships: []
      }
      product_certifications: {
        Row: {
          certification_id: string
          certified_date: string | null
          expiry_date: string | null
          product_id: string
        }
        Insert: {
          certification_id: string
          certified_date?: string | null
          expiry_date?: string | null
          product_id: string
        }
        Update: {
          certification_id?: string
          certified_date?: string | null
          expiry_date?: string | null
          product_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_certifications_certification_id_fkey"
            columns: ["certification_id"]
            isOneToOne: false
            referencedRelation: "certifications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_certifications_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "featured_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_certifications_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_certifications_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_with_taxonomy"
            referencedColumns: ["id"]
          },
        ]
      }
      product_faqs: {
        Row: {
          answer: string
          created_at: string
          display_order: number
          id: string
          is_active: boolean
          product_id: string
          question: string
          updated_at: string
        }
        Insert: {
          answer: string
          created_at?: string
          display_order?: number
          id?: string
          is_active?: boolean
          product_id: string
          question: string
          updated_at?: string
        }
        Update: {
          answer?: string
          created_at?: string
          display_order?: number
          id?: string
          is_active?: boolean
          product_id?: string
          question?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_faqs_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "featured_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_faqs_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_faqs_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_with_taxonomy"
            referencedColumns: ["id"]
          },
        ]
      }
      product_materials: {
        Row: {
          is_primary: boolean | null
          material_id: string
          percentage: number | null
          product_id: string
        }
        Insert: {
          is_primary?: boolean | null
          material_id: string
          percentage?: number | null
          product_id: string
        }
        Update: {
          is_primary?: boolean | null
          material_id?: string
          percentage?: number | null
          product_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_materials_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_materials_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "featured_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_materials_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_materials_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_with_taxonomy"
            referencedColumns: ["id"]
          },
        ]
      }
      product_tags: {
        Row: {
          product_id: string
          tag_id: string
        }
        Insert: {
          product_id: string
          tag_id: string
        }
        Update: {
          product_id?: string
          tag_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_tags_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "featured_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_tags_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_tags_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_with_taxonomy"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_tags_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          },
        ]
      }
      product_vendors: {
        Row: {
          created_at: string | null
          current_price: number | null
          id: string
          is_available: boolean | null
          last_checked: string | null
          product_id: string | null
          product_url: string | null
          vendor_id: string | null
        }
        Insert: {
          created_at?: string | null
          current_price?: number | null
          id?: string
          is_available?: boolean | null
          last_checked?: string | null
          product_id?: string | null
          product_url?: string | null
          vendor_id?: string | null
        }
        Update: {
          created_at?: string | null
          current_price?: number | null
          id?: string
          is_available?: boolean | null
          last_checked?: string | null
          product_id?: string | null
          product_url?: string | null
          vendor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_vendors_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "featured_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_vendors_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_vendors_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_with_taxonomy"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_vendors_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          affiliate_link: string | null
          average_rating: number | null
          bifl_certification: string | null
          bifl_total_score: number | null
          brand_id: string | null
          care_and_maintenance: Json | null
          category_id: string | null
          con_1: string | null
          con_2: string | null
          con_3: string | null
          con_4: string | null
          cons: Json | null
          country_of_origin: string | null
          created_at: string | null
          description: string | null
          dimensions: string | null
          durability_notes: string | null
          durability_score: number | null
          excerpt: string | null
          faq_1_a: string | null
          faq_1_q: string | null
          faq_2_a: string | null
          faq_2_q: string | null
          faq_3_a: string | null
          faq_3_q: string | null
          faq_4_a: string | null
          faq_4_q: string | null
          faq_5_a: string | null
          faq_5_q: string | null
          featured_image_url: string | null
          gallery_images: Json | null
          general_notes: string | null
          id: string
          is_featured: boolean | null
          key_features: Json | null
          lifespan_expectation: number | null
          manufacturer_link: string | null
          manufacturing_notes: string | null
          meta_description: string | null
          meta_title: string | null
          name: string
          optimized_product_description: string | null
          price: number | null
          price_range_id: string | null
          primary_material_id: string | null
          pro_1: string | null
          pro_2: string | null
          pro_3: string | null
          pro_4: string | null
          pros: Json | null
          pros_cons: Json | null
          repairability_notes: string | null
          repairability_score: number | null
          review_count: number | null
          slug: string
          social_notes: string | null
          social_score: number | null
          star_rating: number | null
          status: string | null
          sustainability_notes: string | null
          sustainability_score: number | null
          updated_at: string | null
          use_case: string | null
          verdict_bullets: Json | null
          verdict_summary: string | null
          view_count: number | null
          warranty_notes: string | null
          warranty_score: number | null
          warranty_years: number | null
          weight: string | null
          wordpress_id: number | null
          wordpress_meta: Json | null
        }
        Insert: {
          affiliate_link?: string | null
          average_rating?: number | null
          bifl_certification?: string | null
          bifl_total_score?: number | null
          brand_id?: string | null
          care_and_maintenance?: Json | null
          category_id?: string | null
          con_1?: string | null
          con_2?: string | null
          con_3?: string | null
          con_4?: string | null
          cons?: Json | null
          country_of_origin?: string | null
          created_at?: string | null
          description?: string | null
          dimensions?: string | null
          durability_notes?: string | null
          durability_score?: number | null
          excerpt?: string | null
          faq_1_a?: string | null
          faq_1_q?: string | null
          faq_2_a?: string | null
          faq_2_q?: string | null
          faq_3_a?: string | null
          faq_3_q?: string | null
          faq_4_a?: string | null
          faq_4_q?: string | null
          faq_5_a?: string | null
          faq_5_q?: string | null
          featured_image_url?: string | null
          gallery_images?: Json | null
          general_notes?: string | null
          id?: string
          is_featured?: boolean | null
          key_features?: Json | null
          lifespan_expectation?: number | null
          manufacturer_link?: string | null
          manufacturing_notes?: string | null
          meta_description?: string | null
          meta_title?: string | null
          name: string
          optimized_product_description?: string | null
          price?: number | null
          price_range_id?: string | null
          primary_material_id?: string | null
          pro_1?: string | null
          pro_2?: string | null
          pro_3?: string | null
          pro_4?: string | null
          pros?: Json | null
          pros_cons?: Json | null
          repairability_notes?: string | null
          repairability_score?: number | null
          review_count?: number | null
          slug: string
          social_notes?: string | null
          social_score?: number | null
          star_rating?: number | null
          status?: string | null
          sustainability_notes?: string | null
          sustainability_score?: number | null
          updated_at?: string | null
          use_case?: string | null
          verdict_bullets?: Json | null
          verdict_summary?: string | null
          view_count?: number | null
          warranty_notes?: string | null
          warranty_score?: number | null
          warranty_years?: number | null
          weight?: string | null
          wordpress_id?: number | null
          wordpress_meta?: Json | null
        }
        Update: {
          affiliate_link?: string | null
          average_rating?: number | null
          bifl_certification?: string | null
          bifl_total_score?: number | null
          brand_id?: string | null
          care_and_maintenance?: Json | null
          category_id?: string | null
          con_1?: string | null
          con_2?: string | null
          con_3?: string | null
          con_4?: string | null
          cons?: Json | null
          country_of_origin?: string | null
          created_at?: string | null
          description?: string | null
          dimensions?: string | null
          durability_notes?: string | null
          durability_score?: number | null
          excerpt?: string | null
          faq_1_a?: string | null
          faq_1_q?: string | null
          faq_2_a?: string | null
          faq_2_q?: string | null
          faq_3_a?: string | null
          faq_3_q?: string | null
          faq_4_a?: string | null
          faq_4_q?: string | null
          faq_5_a?: string | null
          faq_5_q?: string | null
          featured_image_url?: string | null
          gallery_images?: Json | null
          general_notes?: string | null
          id?: string
          is_featured?: boolean | null
          key_features?: Json | null
          lifespan_expectation?: number | null
          manufacturer_link?: string | null
          manufacturing_notes?: string | null
          meta_description?: string | null
          meta_title?: string | null
          name?: string
          optimized_product_description?: string | null
          price?: number | null
          price_range_id?: string | null
          primary_material_id?: string | null
          pro_1?: string | null
          pro_2?: string | null
          pro_3?: string | null
          pro_4?: string | null
          pros?: Json | null
          pros_cons?: Json | null
          repairability_notes?: string | null
          repairability_score?: number | null
          review_count?: number | null
          slug?: string
          social_notes?: string | null
          social_score?: number | null
          star_rating?: number | null
          status?: string | null
          sustainability_notes?: string | null
          sustainability_score?: number | null
          updated_at?: string | null
          use_case?: string | null
          verdict_bullets?: Json | null
          verdict_summary?: string | null
          view_count?: number | null
          warranty_notes?: string | null
          warranty_score?: number | null
          warranty_years?: number | null
          weight?: string | null
          wordpress_id?: number | null
          wordpress_meta?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "products_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_price_range_id_fkey"
            columns: ["price_range_id"]
            isOneToOne: false
            referencedRelation: "price_ranges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_primary_material_id_fkey"
            columns: ["primary_material_id"]
            isOneToOne: false
            referencedRelation: "materials"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          cons: Json | null
          content: string | null
          created_at: string | null
          durability_rating: number | null
          helpful_count: number | null
          id: string
          images: Json | null
          overall_rating: number
          product_id: string | null
          pros: Json | null
          repairability_rating: number | null
          reported_count: number | null
          social_rating: number | null
          status: string | null
          still_works: boolean | null
          title: string | null
          updated_at: string | null
          user_email: string
          user_name: string | null
          value_rating: number | null
          verified_purchase: boolean | null
          warranty_rating: number | null
          would_buy_again: boolean | null
          years_owned: number | null
        }
        Insert: {
          cons?: Json | null
          content?: string | null
          created_at?: string | null
          durability_rating?: number | null
          helpful_count?: number | null
          id?: string
          images?: Json | null
          overall_rating: number
          product_id?: string | null
          pros?: Json | null
          repairability_rating?: number | null
          reported_count?: number | null
          social_rating?: number | null
          status?: string | null
          still_works?: boolean | null
          title?: string | null
          updated_at?: string | null
          user_email: string
          user_name?: string | null
          value_rating?: number | null
          verified_purchase?: boolean | null
          warranty_rating?: number | null
          would_buy_again?: boolean | null
          years_owned?: number | null
        }
        Update: {
          cons?: Json | null
          content?: string | null
          created_at?: string | null
          durability_rating?: number | null
          helpful_count?: number | null
          id?: string
          images?: Json | null
          overall_rating?: number
          product_id?: string | null
          pros?: Json | null
          repairability_rating?: number | null
          reported_count?: number | null
          social_rating?: number | null
          status?: string | null
          still_works?: boolean | null
          title?: string | null
          updated_at?: string | null
          user_email?: string
          user_name?: string | null
          value_rating?: number | null
          verified_purchase?: boolean | null
          warranty_rating?: number | null
          would_buy_again?: boolean | null
          years_owned?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "featured_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_with_taxonomy"
            referencedColumns: ["id"]
          },
        ]
      }
      session: {
        Row: {
          createdAt: string
          expiresAt: string
          id: string
          ipAddress: string | null
          token: string
          updatedAt: string
          userAgent: string | null
          userId: string
        }
        Insert: {
          createdAt?: string
          expiresAt: string
          id: string
          ipAddress?: string | null
          token: string
          updatedAt?: string
          userAgent?: string | null
          userId: string
        }
        Update: {
          createdAt?: string
          expiresAt?: string
          id?: string
          ipAddress?: string | null
          token?: string
          updatedAt?: string
          userAgent?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "session_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: ["id"]
          },
        ]
      }
      tags: {
        Row: {
          category: string | null
          created_at: string | null
          id: string
          name: string
          slug: string
          usage_count: number | null
        }
        Insert: {
          category?: string | null
          created_at?: string | null
          id?: string
          name: string
          slug: string
          usage_count?: number | null
        }
        Update: {
          category?: string | null
          created_at?: string | null
          id?: string
          name?: string
          slug?: string
          usage_count?: number | null
        }
        Relationships: []
      }
      user: {
        Row: {
          createdAt: string
          email: string
          emailVerified: boolean
          id: string
          image: string | null
          name: string
          updatedAt: string
        }
        Insert: {
          createdAt?: string
          email: string
          emailVerified?: boolean
          id: string
          image?: string | null
          name: string
          updatedAt?: string
        }
        Update: {
          createdAt?: string
          email?: string
          emailVerified?: boolean
          id?: string
          image?: string | null
          name?: string
          updatedAt?: string
        }
        Relationships: []
      }
      user_favorites: {
        Row: {
          created_at: string | null
          id: string
          product_id: string
          user_email: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          product_id: string
          user_email: string
        }
        Update: {
          created_at?: string | null
          id?: string
          product_id?: string
          user_email?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_favorites_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "featured_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_favorites_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_favorites_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_with_taxonomy"
            referencedColumns: ["id"]
          },
        ]
      }
      user_recently_viewed: {
        Row: {
          id: string
          product_id: string
          user_email: string
          viewed_at: string | null
        }
        Insert: {
          id?: string
          product_id: string
          user_email: string
          viewed_at?: string | null
        }
        Update: {
          id?: string
          product_id?: string
          user_email?: string
          viewed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_recently_viewed_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "featured_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_recently_viewed_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_recently_viewed_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products_with_taxonomy"
            referencedColumns: ["id"]
          },
        ]
      }
      vendors: {
        Row: {
          affiliate_program: boolean | null
          commission_rate: number | null
          created_at: string | null
          id: string
          name: string
          reputation_score: number | null
          return_policy: string | null
          shipping_info: string | null
          slug: string
          website: string | null
        }
        Insert: {
          affiliate_program?: boolean | null
          commission_rate?: number | null
          created_at?: string | null
          id?: string
          name: string
          reputation_score?: number | null
          return_policy?: string | null
          shipping_info?: string | null
          slug: string
          website?: string | null
        }
        Update: {
          affiliate_program?: boolean | null
          commission_rate?: number | null
          created_at?: string | null
          id?: string
          name?: string
          reputation_score?: number | null
          return_policy?: string | null
          shipping_info?: string | null
          slug?: string
          website?: string | null
        }
        Relationships: []
      }
      verification: {
        Row: {
          createdAt: string | null
          expiresAt: string
          id: string
          identifier: string
          updatedAt: string | null
          value: string
        }
        Insert: {
          createdAt?: string | null
          expiresAt: string
          id: string
          identifier: string
          updatedAt?: string | null
          value: string
        }
        Update: {
          createdAt?: string | null
          expiresAt?: string
          id?: string
          identifier?: string
          updatedAt?: string | null
          value?: string
        }
        Relationships: []
      }
    }
    Views: {
      featured_products: {
        Row: {
          bifl_total_score: number | null
          brand_name: string | null
          brand_slug: string | null
          category_name: string | null
          category_slug: string | null
          created_at: string | null
          featured_image_url: string | null
          id: string | null
          material_name: string | null
          name: string | null
          price_range_name: string | null
          slug: string | null
        }
        Relationships: []
      }
      products_with_taxonomy: {
        Row: {
          affiliate_link: string | null
          bifl_certification: string | null
          bifl_total_score: number | null
          brand_id: string | null
          brand_name: string | null
          brand_slug: string | null
          category_id: string | null
          category_name: string | null
          category_slug: string | null
          certification_names: string[] | null
          country_of_origin: string | null
          created_at: string | null
          description: string | null
          durability_score: number | null
          excerpt: string | null
          featured_image_url: string | null
          id: string | null
          is_featured: boolean | null
          lifespan_expectation: number | null
          material_name: string | null
          name: string | null
          price: number | null
          price_range_id: string | null
          price_range_name: string | null
          repairability_score: number | null
          slug: string | null
          social_score: number | null
          status: string | null
          sustainability_score: number | null
          tag_names: string[] | null
          use_case: string | null
          warranty_score: number | null
        }
        Relationships: [
          {
            foreignKeyName: "products_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_price_range_id_fkey"
            columns: ["price_range_id"]
            isOneToOne: false
            referencedRelation: "price_ranges"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      calculate_bifl_score: {
        Args:
          | {
              dur_score: number
              rep_score: number
              soc_score: number
              sus_score: number
              war_score: number
            }
          | {
              dur_score: number
              rep_score: number
              soc_score: number
              sus_score: number
              war_score: number
            }
        Returns: number
      }
      increment_helpful_count: {
        Args: { review_id: string }
        Returns: undefined
      }
      increment_report_count: {
        Args: { review_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
